"""
Django settings for forallbackpack project.

Generated by 'django-admin startproject' using Django 1.10.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '9as8j*8l%4&v9r170eyz(a(!bs302c$4e*p_tso7^vgzy(jkal'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'lti_provider',
    'compressor',
    'reversion',
    'rest_framework',
    'rest_framework_tracking',
    'tracking',
    'bootstrap3',
    'api',
    'auth.apps.AuthConfig',
    'forallbackpack',
    'oauth2_provider',
    'corsheaders',
    'widget_tweaks',
    #"sslserver",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'forallbackpack.middleware.VisitorTrackingMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'oauth2_provider.middleware.OAuth2TokenMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    #'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'forallbackpack.middleware.TrackingMiddleware',
]

ROOT_URLCONF = 'forallbackpack.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'forallbackpack', 'templates')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'forallbackpack.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'"
        },
        'NAME': 'forallbackpack',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': '',
        'PORT': '',
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    {
        'NAME': 'forallbackpack.validation.UpperAndNumberPasswordValidator',
    }
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATICFILES_FINDERS = ("django.contrib.staticfiles.finders.FileSystemFinder",
                       "django.contrib.staticfiles.finders.AppDirectoriesFinder",
                       'compressor.finders.CompressorFinder')

STATIC_URL = 'http://127.0.0.1/forallbackpack/forallbackpack/static/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

LOCAL_MEDIA_ROOT = os.path.join(BASE_DIR, 'media/') #For eventual AWS integration

STATIC_ROOT = os.path.join(BASE_DIR, 'forallbackpack/static/')

MEDIA_URL = 'http://127.0.0.1/forallbackpack/media/'

LOGIN_URL = '/login/'

# REDIRECT TO NEW APP
LOGIN_REDIRECT_URL = 'http://localhost:8080'

LOGOUT_REDIRECT_URL = '/'

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

DEFAULT_FROM_EMAIL = 'notice@forallschools.com'

TWILIO_ACCOUNT_SID = ''
TWILIO_AUTO_TOKEN  = ''
TWILIO_PHONE_NUMBER = ''

DROPBOX_APP_KEY = ''
DROPBOX_APP_SECRET = ''

GOOGLE_OAUTH2_CLIENT_ID = ''
GOOGLE_OAUTH2_CLIENT_SECRET = ''

ONEDRIVE_API_CLIENTID = ''
ONEDRIVE_API_SECRET = ''

# django-oauth-toolkit

OAUTH2_PROVIDER = {
    # this is the list of available scopes
    'SCOPES': {'read': 'Read scope', 'write': 'Write scope', 'groups': 'Access to your groups'},
    # Use custom validator for password grant type user validation
    'OAUTH2_VALIDATOR_CLASS': 'auth.validators.OAuth2Validator',
}

# django-rest-framework

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'oauth2_provider.ext.rest_framework.OAuth2Authentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        #'rest_framework.permissions.IsAuthenticated',
        'api.permissions.APIPermission',
    ),
    'EXCEPTION_HANDLER': 'api.views.custom_exception_handler',
}

# django-tracking2
# https://github.com/bruth/django-tracking2#settings

TRACK_PAGEVIEWS = True

TRACK_IGNORE_URLS = (
    '^(?!share)|(?!assertion)/.*',
)

TRACK_REFERER = True

TRACK_QUERY_STRING = True

# django-cors-middleware

CORS_ORIGIN_ALLOW_ALL = True

AUTHENTICATION_BACKENDS = (
    'oauth2_provider.backends.OAuth2Backend',
    'django.contrib.auth.backends.ModelBackend',
    'auth.lti.CustomLTIBackend',
)



LTI_TOOL_CONFIGURATION = {
    'title': 'ForAllBackpacks',
    'description': 'ForAllBackpacks is an open badges backpack.',
    'launch_url': 'lti/',
    'embed_url': '/',
    'embed_icon_url': '',
    'embed_tool_id': '',
    'landing_url': '/',
    'course_aware': False,
    'course_navigation': False,
    'navigation':True,
    'new_tab': False,
    'frame_width': 1024,
    'frame_height': 768,
    'assignments': {}
}

PYLTI_CONFIG = {
    'consumers': {
        'KEY': {
            'secret': 'SECRET'
        }
    }
}
