# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-31 16:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField(auto_now_add=True)),
                ('remote_addr', models.GenericIPAddressField(help_text='Remote IP address of request')),
                ('credentials', models.TextField(blank=True, help_text='Credentials passed to authenticate for failure')),
                ('user', models.ForeignKey(blank=True, help_text='User that logged in or None for failure', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UserLogin',
            },
        ),
    ]
