# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 01:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('external_id', models.TextField(blank=True)),
                ('badge_id', models.TextField(blank=True, null=True)),
                ('external_badge_id', models.TextField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('student_name', models.TextField(blank=True)),
                ('badge_name', models.TextField(blank=True)),
                ('badge_description', models.TextField(blank=True)),
                ('badge_criteria', models.TextField(blank=True)),
                ('badge_image', models.TextField(blank=True, null=True)),
                ('badge_allow_send_backpack', models.BooleanField(default=True)),
                ('badge_identifier', models.CharField(blank=True, max_length=256)),
                ('badge_points', models.IntegerField(default=0)),
                ('badge_months_valid', models.IntegerField(default=0)),
                ('badge_certificate_serialized', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AwardCustom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_private', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=256)),
                ('value', models.TextField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, max_length=255, null=True, upload_to='files/evidence')),
                ('hyperlink', models.TextField(blank=True, null=True)),
                ('label', models.CharField(max_length=256)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forallbackpack.Award')),
            ],
        ),
    ]
