# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 13:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forallbackpack', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='badge_allow_send_backpack',
        ),
        migrations.RemoveField(
            model_name='award',
            name='badge_certificate_serialized',
        ),
        migrations.RemoveField(
            model_name='award',
            name='badge_identifier',
        ),
        migrations.RemoveField(
            model_name='award',
            name='badge_months_valid',
        ),
        migrations.RemoveField(
            model_name='award',
            name='badge_points',
        ),
    ]
