# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forallbackpack', '0002_auto_20170301_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='assertion_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='award',
            name='baked_image_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='award',
            name='org_issued_name',
            field=models.TextField(blank=True),
        ),
    ]
