# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 23:19
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('forallbackpack', '0008_auto_20170407_0103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('prefix', models.CharField(default='', max_length=10)),
                ('key', models.CharField(max_length=256)),
                ('secret', models.CharField(max_length=256)),
                ('url', models.URLField(help_text='Default base URL for constructing API endpoints', verbose_name='URL')),
                ('url_verify_account_claim_code', models.CharField(blank=True, default='/user/verify_account_claim_code/', help_text='POST account claim code for verification', max_length=256)),
                ('url_claim_account', models.CharField(blank=True, default='/user/claim_account/', help_text='POST redeeemed account claim code', max_length=256)),
            ],
        ),
    ]
