# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forallbackpack', '0010_auto_20170513_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='has_forall_permissions',
            field=models.BooleanField(default=False, help_text='Has elevated ForAll permissions'),
        ),
    ]
