# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 17:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forallbackpack', '0011_registration_has_forall_permissions'),
        ('forallbackpack', '0011_tag'),
    ]

    operations = [
    ]
