# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forallbackpack', '0013_auto_20170525_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='badge_image_data_uri',
            field=models.TextField(blank=True, help_text='Data URL for badge image thumbnail'),
        ),
        migrations.AddField(
            model_name='award',
            name='tags',
            field=models.ManyToManyField(blank=True, to='forallbackpack.Tag'),
        ),
    ]
