# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forallbackpack', '0014_auto_20170525_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
