# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-27 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forallbackpack', '0015_award_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='badge_version',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
