# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forallbackpack', '0016_award_badge_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='badge_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='files/evidence'),
        ),
    ]
