# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forallbackpack', '0019_authtoken_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='issuer_org_name',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='award',
            name='issuer_org_origin',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='award',
            name='issuer_org_url',
            field=models.TextField(blank=True),
        ),
    ]
