# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-07 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forallbackpack', '0020_auto_20170530_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='url_award_claim',
            field=models.CharField(blank=True, default='/api/award/claim/', help_text='POST award claim code', max_length=256),
        ),
    ]
