# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-07 22:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forallbackpack', '0021_registration_url_award_claim'),
    ]

    operations = [
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.IntegerField(choices=[(0, 'Public Link'), (1, 'HTML Embed'), (2, 'Twitter'), (3, 'Pinterest'), (4, 'Google Plus'), (5, 'LinkedIn')], default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('views', models.IntegerField(default=0)),
                ('object_id', models.UUIDField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('tags', models.ManyToManyField(blank=True, to='forallbackpack.Tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
