# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-08 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forallbackpack', '0023_auto_20170607_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='type',
            field=models.IntegerField(choices=[(0, 'Public Link'), (1, 'HTML Embed'), (2, 'Facebook'), (3, 'Twitter'), (4, 'Pinterest'), (5, 'Google Plus'), (6, 'LinkedIn')], default=0),
        ),
    ]
