# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-09 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forallbackpack', '0024_auto_20170608_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='share',
            name='type',
        ),
        migrations.AddField(
            model_name='share',
            name='type_embed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='share',
            name='type_facebook',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='share',
            name='type_googleplus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='share',
            name='type_link',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='share',
            name='type_linkedin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='share',
            name='type_pinterest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='share',
            name='type_twitter',
            field=models.BooleanField(default=False),
        ),
    ]
