# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-14 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forallbackpack', '0026_useraccount_userapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='url_award_claim',
            field=models.CharField(blank=True, default='/api/user/claim_badge/', help_text='POST award claim code', max_length=256),
        ),
    ]
