# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 22:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forallbackpack', '0027_auto_20170614_2151'),
        ('forallbackpack', '0027_auto_20170614_2144'),
    ]

    operations = [
    ]
