# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-15 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forallbackpack', '0028_merge_20170614_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapp',
            name='app_id',
            field=models.CharField(default='', max_length=256),
        ),
    ]
