# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-20 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forallbackpack', '0029_userapp_app_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='share',
            name='type_embed',
        ),
        migrations.RemoveField(
            model_name='share',
            name='type_facebook',
        ),
        migrations.RemoveField(
            model_name='share',
            name='type_googleplus',
        ),
        migrations.RemoveField(
            model_name='share',
            name='type_link',
        ),
        migrations.RemoveField(
            model_name='share',
            name='type_linkedin',
        ),
        migrations.RemoveField(
            model_name='share',
            name='type_pinterest',
        ),
        migrations.RemoveField(
            model_name='share',
            name='type_twitter',
        ),
        migrations.AddField(
            model_name='share',
            name='type',
            field=models.CharField(choices=[('type_link', 'Link'), ('type_embed', 'Embed'), ('type_facebook', 'Facebook'), ('type_twitter', 'Twitter'), ('type_interest', 'Pinterest'), ('type_googleplus', 'Google Plus'), ('type_linkedin', 'LinkedIn')], default='type_link', max_length=20),
        ),
        migrations.AlterField(
            model_name='userapp',
            name='app_id',
            field=models.CharField(max_length=256),
        ),
    ]
