# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-21 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forallbackpack', '0031_auto_20170620_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='issuer_org_email',
            field=models.TextField(blank=True),
        ),
    ]
