# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-24 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forallbackpack', '0033_userprofile_is_claimfs'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_claimrcoe',
            field=models.IntegerField(default=0),
        ),
    ]
