# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-07 16:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forallbackpack', '0034_userprofile_is_claimrcoe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('text', models.TextField(blank=True, default='')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forallbackpack.Entry')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='share',
            name='tags',
        ),
        migrations.AlterField(
            model_name='tag',
            name='type',
            field=models.IntegerField(choices=[(0, 'Award'), (1, 'Entry')], default=0),
        ),
        migrations.AddField(
            model_name='entry',
            name='tags',
            field=models.ManyToManyField(blank=True, to='forallbackpack.Tag'),
        ),
        migrations.AddField(
            model_name='entry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
