# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-08 16:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forallbackpack', '0035_auto_20170907_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='updated_dt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='forallbackpack.Entry'),
        ),
    ]
