# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-12 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forallbackpack', '0040_attachment_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='hyperlink',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='label',
            field=models.CharField(max_length=256),
        ),
    ]
