# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-18 18:06
from __future__ import unicode_literals

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    """Initialize primary `UserEmail` instances as needed"""
    User = apps.get_model('auth', 'User')
    UserEmail = apps.get_model('forallbackpack', 'UserEmail')

    for user in User.objects.filter(is_superuser=False):
        if UserEmail.objects.filter(user=user).count():
        #if user.useremail_set.count():
            try:
                user_email = UserEmail.objects.get(user=user, email=user.email)
            except UserEmail.DoesNotExist:
                user_email = user.useremail_set.first()

            if not user_email.is_primary:
                user_email.is_primary = True
                user_email.save()
        else:
            is_validated = user.userapp_set.count() > 0

            user_email = UserEmail.objects.create(
                user=user,
                email=user.email,
                is_validated=is_validated,
                is_primary=True
            )


class Migration(migrations.Migration):

    dependencies = [
        ('forallbackpack', '0042_auto_20170915_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='useremail',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(forwards_func, reverse_code=migrations.RunPython.noop),
    ]
