# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-21 18:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forallbackpack', '0044_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forallbackpack.Event'),
        ),
    ]
