# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-21 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forallbackpack', '0045_userprofile_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='url_claim_event',
            field=models.CharField(blank=True, default='/api/user/claim_event/', help_text='POST redeeemed event badge', max_length=256),
        ),
    ]
