# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-21 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forallbackpack', '0047_auto_20170921_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='event_class_code',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
