# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-26 17:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forallbackpack', '0048_userprofile_event_class_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useremail',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
