# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-26 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forallbackpack', '0049_auto_20170926_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='notify_type',
            field=models.IntegerField(choices=[(0, 'Email'), (1, 'SMS'), (2, 'Email & SMS')], default=0),
        ),
    ]
