# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-26 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forallbackpack', '0050_userprofile_notify_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='useremail',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
