# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-27 17:48
from __future__ import unicode_literals

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    """Initialize `Award`.`student_email`"""
    Award = apps.get_model('forallbackpack', 'Award')

    for award in Award.objects.filter(student_email=''):
        award.student_email = award.user.email
        award.save()

class Migration(migrations.Migration):

    dependencies = [
        ('forallbackpack', '0052_useremail_created_dt'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='student_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.RunPython(forwards_func, reverse_code=migrations.RunPython.noop),
    ]
