# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-28 14:36
from __future__ import unicode_literals

from django.db import migrations

def forwards_func(apps, schema_editor):
    """Initialize primary `UserEmail` instances as needed"""
    User = apps.get_model('auth', 'User')
    UserEmail = apps.get_model('forallbackpack', 'UserEmail')
    
    for user in User.objects.filter(is_superuser=False):
        if user.useremail_set.count():
            try:
                user_email = UserEmail.objects.get(user=user, email=user.email)
            except UserEmail.DoesNotExist:
                user_email = user.useremail_set.first()
          
            if not user_email.is_primary:
                user_email.is_primary = True
                user_email.save()
        else:        
            is_validated = user.userapp_set.count() > 0
            
            user_email = UserEmail.objects.create(
                user=user, 
                email=user.email, 
                is_validated=is_validated, 
                is_primary=True
            )

class Migration(migrations.Migration):

    dependencies = [
        ('forallbackpack', '0053_award_student_email'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_code=migrations.RunPython.noop),
    ]
