# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-29 16:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forallbackpack', '0054_init_user_emails'),
        ('forallbackpack', '0042_attachment_data_uri'),
    ]

    operations = [
    ]
