# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-03 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forallbackpack', '0054_init_user_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_pledge',
            field=models.BooleanField(default=False),
        ),
    ]
