# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-03 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forallbackpack', '0055_event_is_pledge'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
