# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-04 20:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forallbackpack', '0058_entry_award'),
        ('forallbackpack', '0042_attachment_data_uri'),
    ]

    operations = [
    ]
