# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-04 20:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forallbackpack', '0060_registration_url_pledge'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='event',
            field=models.ForeignKey(blank=True, help_text='For pledgable badges', null=True, on_delete=django.db.models.deletion.CASCADE, to='forallbackpack.Event'),
        ),
    ]
