# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-06 18:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forallbackpack', '0055_merge_20170929_1601'),
        ('forallbackpack', '0062_auto_20171004_2159'),
    ]

    operations = [
    ]
