# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-24 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forallbackpack', '0064_event_badge_criteria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='prefix',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
