# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-09 16:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forallbackpack', '0064_event_badge_criteria'),
        ('forallbackpack', '0063_merge_20171006_1842'),
    ]

    operations = [
    ]
