# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-11 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forallbackpack', '0065_merge_20171009_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
