# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-11 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forallbackpack', '0066_entry_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='section',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
