# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-31 14:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forallbackpack', '0068_auto_20171012_1457'),
        ('forallbackpack', '0065_auto_20171024_1700'),
    ]

    operations = [
    ]
