# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-08 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forallbackpack', '0069_merge_20171031_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='badge_image',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='files/badges'),
        ),
    ]
