# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-20 20:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('forallbackpack', '0070_auto_20180108_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardEndorsement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('url', models.URLField(blank=True, default='')),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('image_url', models.URLField(blank=True, default='')),
                ('image_data_uri', models.TextField(blank=True, default='', help_text='Data URI for endorsement image thumbnail')),
            ],
            options={
                'verbose_name': 'AwardEndorsement',
            },
        ),
        migrations.AlterField(
            model_name='award',
            name='badge_image_data_uri',
            field=models.TextField(blank=True, help_text='Data URI for badge image thumbnail'),
        ),
        migrations.AddField(
            model_name='awardendorsement',
            name='award',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forallbackpack.Award'),
        ),
    ]
