# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-15 20:40
from __future__ import unicode_literals

from django.db import migrations
from django.db.models import CharField
from django.db.models.functions import Length


def forwards_func(apps, schema_editor):
    """Prepend first Registration.prefix to User.username"""    
    CharField.register_lookup(Length, 'length')

    User = apps.get_model('auth', 'User')

    qs = User.objects.filter(is_superuser=False)\
        .exclude(username__contains='@')\
        .exclude(username__length=32)
        
    for user in qs:        
        useraccount = user.useraccount_set.first()
        if not useraccount:
            continue

        username = '%s_%s' % (useraccount.registration.prefix, user.username)
        
        user.username = username
        user.save()
 
class Migration(migrations.Migration):

    dependencies = [
        ('forallbackpack', '0070_auto_20180108_2245'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_code=migrations.RunPython.noop),
    ]
