# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-07 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forallbackpack', '0070_auto_20180108_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='revoked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='award',
            name='revoked_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
