# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-09 17:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forallbackpack', '0070_auto_20180108_2245'),
        ('forallbackpack', '0069_merge_20171031_2121'),
    ]

    operations = [
    ]
