# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-09 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forallbackpack', '0071_auto_20180207_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='verified_dt',
            field=models.DateTimeField(blank=True, default=None, help_text='Date and time of last successful verification', null=True),
        ),
    ]
