# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-27 16:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forallbackpack', '0071_auto_20180207_2149'),
        ('forallbackpack', '0071_merge_20180109_1750'),
    ]

    operations = [
    ]
