# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-20 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forallbackpack', '0071_auto_20180320_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='awardendorsement',
            name='image_url',
        ),
        migrations.AddField(
            model_name='awardendorsement',
            name='image',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='files/awardendorsement'),
        ),
        migrations.AlterField(
            model_name='awardendorsement',
            name='image_data_uri',
            field=models.TextField(blank=True, default='', help_text='Data URI for image thumbnail'),
        ),
    ]
