# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-21 19:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forallbackpack', '0072_auto_20180320_2045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='awardendorsement',
            old_name='email',
            new_name='issuer_email',
        ),
        migrations.RenameField(
            model_name='awardendorsement',
            old_name='image',
            new_name='issuer_image',
        ),
        migrations.RenameField(
            model_name='awardendorsement',
            old_name='image_data_uri',
            new_name='issuer_image_data_uri',
        ),
        migrations.RenameField(
            model_name='awardendorsement',
            old_name='name',
            new_name='issuer_name',
        ),
        migrations.RenameField(
            model_name='awardendorsement',
            old_name='url',
            new_name='issuer_url',
        ),
        migrations.AddField(
            model_name='awardendorsement',
            name='issued_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
