# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-09 22:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forallbackpack', '0072_award_verified_dt'),
        ('forallbackpack', '0072_merge_20180227_1604'),
    ]

    operations = [
    ]
