# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-21 23:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forallbackpack', '0073_auto_20180321_1904'),
        ('forallbackpack', '0072_award_verified_dt'),
    ]

    operations = [
    ]
