# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-15 23:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forallbackpack', '0071_auto_20180315_2040'),
        ('forallbackpack', '0073_merge_20180309_2236'),
    ]

    operations = [
    ]
