# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-23 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forallbackpack', '0074_merge_20180321_2313'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='awardendorsement',
            options={'ordering': ['issuer_name'], 'verbose_name': 'AwardEndorsement'},
        ),
        migrations.AlterField(
            model_name='awardendorsement',
            name='issuer_url',
            field=models.URLField(),
        ),
    ]
