# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-23 15:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forallbackpack', '0075_auto_20180323_1530'),
        ('forallbackpack', '0074_merge_20180315_2332'),
    ]

    operations = [
    ]
