# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-02 17:39
from __future__ import unicode_literals

from django.db import migrations
from django.utils import timezone

def forwards_func(apps, schema_editor):
    """Initialize `verified_dt` for FS-issued Awards"""
    Award = apps.get_model('forallbackpack', 'Award')
    
    Award.objects.filter(issuer_org_url='http://www.forallsystems.com')\
        .update(verified_dt=timezone.now())

class Migration(migrations.Migration):

    dependencies = [
        ('forallbackpack', '0076_merge_20180323_1535'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_code=migrations.RunPython.noop),
    ]
